### ISSUE TITLE
[Feature Request] Jellyfin support

### ISSUE THREAD

**Issue by kbirger** [Boerderij/Varken#215] opened 2021-10-04 20:26 UTC
Jellyfin is a popular FOSS software similar to Plex. It's extremely feature rich and has a huge userbase. It would be great to support it here.

**Comment by samwiseg0** [comment] 2021-10-04 21:05
None of the devs use jellyfin. We will not be implementing this but we do accepts PRs. That said. We would want a tautulli alternative for jellyfin in order to integrate. To our knowledge a stable implementation of this does not exist today. 

Duplicate of https://github.com/Boerderij/Varken/issues/200

**Closed as completed by samwiseg0** 2021-10-04 21:05 UTC
Labels: awaiting-triage
