### ISSUE TITLE
[Feature Request] Unifi Integration

### ISSUE THREAD

**Issue by sconnery** [Boerderij/Varken#79] opened 2019-01-02 09:30 UTC
Hey Guys,
This project is great,
Can we somehow integrate unifi applicances in lieu of cisco asa ?

thanks 
steve

**Comment by DirtyCajunRice** [comment] 2019-01-02 17:09
I have the UniFi controller installed as a service. It looks like the api documentation is solely a reverse engineer project which does worry me a bit but i can play around with it. The currently reverse engineered documentation is [here](https://ubntwiki.com/products/software/unifi-controller/api). I will tentatively approve this on the grounds that if it is possible to pull I think it would be good, but after I spend some time digging, i might find that this is not documented well enough. 

In addition, i do not use it as a gateway so i might have some api responses i cannot reproduce. In the event that this is the case, i will need assistance with queries from yourself or someone with the hardware.

cheers!

**Comment by sconnery** [comment] 2019-01-03 07:41
Hey Nicholas,

That should the DPI Screen, Which is the useage of my gateway
IE: 2tb on torrents, 2tb on xbox updates etc

https://unifi:8443/manage/site/default/dashboard
this shows the dash board (bandiwth usage and hadware usage

The unifi controller server does offer snmp readouts? That may help?

I am also a member of the beta community who might be interested?

There is also this existing dashboard
Maybe with there permission(not sure if open source)
We can use that data?

https://grafana.com/dashboards/6885

I am online at that time.

Name on discord is corporatesteve

I am in Australia in Sydney.

**Comment by DirtyCajunRice** [comment] 2019-01-03 14:49
That was a link to your controller but not an image. 
Keep in mind we don’t want metrics for all transferred data in the house as that’s not relevant or helpful. We are looking for wan in/out speed and possibly data transferred by San for x time. 
That dashboard just looks at exported data. So wouldn’t be helpful to us. 
We will never poll snmp, it’s not 2002 ;)

If you can send pictures, wonderful. If not and would rather do it on discord that’s fine too! 

Thanks


<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by sconnery** [comment] 2019-01-03 19:38
Hahaha . That's funny . I am happy to discord.  Let's figure out a time .

Thank you


Many Thanks,



Steven Connery



Steven Connery

Owner

Static Group

Ph: 1300 366 638<tel:1300%20366%20638>



URL: www.staticcomputers.com<http://www.staticcomputers.com/>/ www.staticgroup.com.au

––––––––––––––––––––––––––––––

Unencrypted electronic mail is not secure and may not be authentic.
If you have any doubts as to the contents please telephone to confirm.

This electronic transmission including any attachments is intended only
for those to whom it is addressed. It may contain copyright material or
information that is confidential, privileged or exempt from disclosure by law.
Any claim to privilege is not waived or lost by reason of mistaken transmission
of this information. If you are not the intended recipient you must not
distribute or copy this transmission and should please notify the sender.
Your costs for doing this will be reimbursed by the sender.

We do not accept liability in connection with computer virus, data corruption,
delay, interruption, unauthorised access or unauthorised amendment.

________________________________

**Closed** 2019-01-07 16:30 UTC
Labels: approved, enhancement, help-wanted

**Comment by johntdyer** [comment] 2019-03-19 03:09
What is the USG_Name ? I have tried half a dozen names and none work...

```
root@ubuntu:/opt/Varken# /opt/Varken/varken-venv/bin/python /opt/Varken/Varken.py
2019-03-18 23:09:07 : INFO : Varken : Starting Varken...
2019-03-18 23:09:07 : INFO : Varken : Data folder is "/opt/Varken/data"
2019-03-18 23:09:07 : INFO : Varken : Linux 4.15.0-45-generic (#48-Ubuntu SMP Tue Jan 29 16:28:13 UTC 2019 - Ubuntu 18.04 bionic)
2019-03-18 23:09:07 : INFO : Varken : Python 3.6.7 (default, Oct 22 2018, 11:32:17)
[GCC 8.2.0]
2019-03-18 23:09:07 : INFO : Varken : Varken v1.6.6-master
2019-03-18 23:09:07 : INFO : iniparser : SONARR_SERVER_IDS disabled.
2019-03-18 23:09:07 : INFO : iniparser : RADARR_SERVER_IDS disabled.
2019-03-18 23:09:07 : INFO : iniparser : OMBI_SERVER_IDS disabled.
2019-03-18 23:09:07 : INFO : helpers : TAUTULLI_SERVER_IDS : [1]
2019-03-18 23:09:07 : INFO : iniparser : SICKCHILL_SERVER_IDS disabled.
2019-03-18 23:09:07 : INFO : helpers : UNIFI_SERVER_IDS : [1]
2019-03-18 23:09:07 : INFO : dbmanager : Influxdb version: 1.7.4
2019-03-18 23:09:07 : INFO : helpers : Opening persistent connection to GeoLite2 DB...
2019-03-18 23:09:08 : INFO : __init__ : Running *all* 4 jobs with 0s delay inbetween
2019-03-18 23:09:08 : INFO : __init__ : Running job Every 12 to 24 hours do put(<bound method GeoIPHandler.update of <varken.helpers.GeoIPHandler object at 0x7f641e4b2c18>>) (last run: [never], next run: 2019-03-19 12:09:07)
2019-03-18 23:09:08 : INFO : __init__ : Running job Every 30 seconds do put(<bound method TautulliAPI.get_activity of <tautulli-1>>) (last run: [never], next run: 2019-03-18 23:09:37)
2019-03-18 23:09:08 : INFO : __init__ : Running job Every 3600 seconds do put(<bound method TautulliAPI.get_stats of <tautulli-1>>) (last run: [never], next run: 2019-03-19 00:09:07)
2019-03-18 23:09:08 : INFO : __init__ : Running job Every 300 seconds do put(<bound method UniFiAPI.get_usg_stats of <unifi-1>>) (last run: [never], next run: 2019-03-18 23:14:08)
2019-03-18 23:09:08 : INFO : helpers : This url doesnt even resolve: http://********:8181/api/v2?apikey=********b****************root&cmd=get_activity
2019-03-18 23:09:08 : INFO : helpers : This url doesnt even resolve: http://********:8181/api/v2?apikey=********b****************root&cmd=get_libraries
2019-03-18 23:09:08 : ERROR : unifi : Could not find a USG named Home from your UniFi Controller

```

**Comment by samwiseg0** [comment] 2019-03-19 03:10
@johntdyer issues is not the place for support. Please use Discord.
